### ISSUE TITLE
Filehandle leak in get_tempfile method.

### ISSUE THREAD

**Issue by pobocks** [lyrasis/aspace-jsonmodel-from-format#1]
Hi,

While ingest Harvard's GINORMOUS block of EADs, we were getting a bunch of "too many open files" errors.  I've done some digging, and I think the problem is [here](https://github.com/lyrasis/aspace-jsonmodel-from-format/blob/master/backend/controllers/jsonmodel_from_format_controller.rb#L43).  

Basically, the hack to keep ahold of those filehandles, works out fine in the spec method they're taken from, bc specs get run against an instance, which then gets shut down, freeing all the handles.  But on a production instance, $icky_hack_to_avoid_gc never goes away, so this represents a long-term resource leak.  You probably won't hit it as fast as we do, but eventually you'll hit open file limit, and that'll basically halt operation of ArchivesSpace until restart.

Since you're actually passing the tmpfile back out of the function, and I think holding onto it until you use it, you can probably just drop the offending lines.  I'll do more investigation tomorrow or the next day - I'm out sick, but I checked on our ingest and figured this out, and wanted to let you know ASAP.

**Comment by mark-cooper** [comment]
Thanks for the feedback! Haven't looked at this in a while ...

So, this is 100% untested but I hastily cobbled this together:

https://github.com/lyrasis/aspace-jsonmodel-from-format/compare/delete_generated_files?expand=1

Clearing up the tmp files after they've been used.

**Comment by pobocks** [comment]
Hiya,

I'm not sure this is gonna work - the issue isn't that the filesystem is
filling up, but that ArchivesSpace is holding on to file descriptors - if
I'm reading this right, even if you unlink a tmpfile right after using it,
the handle stays open and usable:
http://ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#class-Tempfile-label-Unlink+after+creation

- Dave

**Comment by mark-cooper** [comment]
So using `tmpfile.close(true)` should do it?

http://ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#method-i-close

**Comment by pobocks** [comment]
Yeah, as long as it happens after the contents are used, that should work.

- Dave

**Comment by pobocks** [comment]
Thanks for being so responsive on this - I'm gonna verify this on my end, I'll let you know if I hit any snags!

**Comment by mark-cooper** [comment]
No problem =) ... hope it works out for you now.
