### ISSUE TITLE
Currently, there's no way to support custom importers that don't override a default importer.

### ISSUE THREAD

**Issue by pobocks** [lyrasis/aspace-jsonmodel-from-format#3]
Looking at the code, there's no way I can see to say "use this custom importer;" the various importers for each type of converter are hardcoded via classnames.

The use case I have in mind here is the one Bentley has, where they've customized their EAD importer, and instead of their plugin overriding the ead_converter.rb directly, they created a new converter that inherits from it, and did their customizations there. 

I have a couple ideas of how to implement support for this, mostly variations on:
1. Implementing a "fallback" option, where an option not being present in the converter tree grabs a converter by some kind of documented name->class conversion, and then does an is_a? check against the converter parent classes to determine whether it should parse as csv or xml
2. A separate route for custom converters, with an additional step defining xml or csv nature of the converter.

**Comment by pobocks** [comment]
For reference of anyone looking at this, I'm currently working around this by inheriting from the EADConverter, then redefining the EADConverter constant to point at my new importer class.

**Comment by mark-cooper** [comment]
Another idea that comes to mind is to push the converter_tree into AppConfig in some form, maybe even entirely:

```
AppConfig[:converter_tree] = {
      accession: {
        csv: ->(content) { init_converter(AccessionConverter, :parse_as_csv, content) },
      },
      agent: {
        eac: ->(content) { init_converter(EACConverter, :parse_as_xml, content) },
      },
      digital_object: {
        csv: ->(content) { init_converter(DigitalObjectConverter, :parse_as_csv, content) },
      },
      resource: {
        ead: ->(content) { init_converter(EADConverter, :parse_as_xml, content) },
        marcxml: ->(content) { init_converter(MarcXMLConverter, :parse_as_xml, content) },
      },
}

###
def converter_tree
      AppConfig[:converter_tree]
end
```

So there'll be a default implementation and something that can be overridden easily ...

**Comment by mark-cooper** [comment]
Completely untested but I think something like this would be a worthy refactoring:

https://github.com/lyrasis/aspace-jsonmodel-from-format/compare/support_custom_importers?expand=1

Will pick up as time allows ...

**Comment by pobocks** [comment]
Hmmm.  I think the overall plan is sound, provided there isn't order-dependence between plugin definition and config.rb loading (like, I'm not sure how this works, since plugins are included based on contents of config - can plugin inits safely depend on config?)

**Comment by mark-cooper** [comment]
I believe they can ... the config file is parsed multiple times as aspace fires up and how / when things are accessed depends on what is being done. It may be the case that overriding AppConfig settings provided via a plugin in config.rb only works for this reason and may really be a side effect of that process (which would be sloppy), but there are precedents out there for doing it (iirc). Or else this may be better:

```
unless AppConfig.has_key?(:converter_tree)
  # no conveter_tree in config.rb so define default converter_tree
end
```

**Comment by pobocks** [comment]
Whatever the solution, I think being able to define partial trees is
useful, and being able to define them in AppConfig seems like the right way
to me.

The other thing that just occurred to me re: config - this ought to be done
in a way where it doesn't make plugins which define converters
order-dependent on jsonmodel-from-format or vice versa; I'm trying to
figure out if that's a worry, or if the global nature of constants means
I'm borrowing trouble.

**Comment by mark-cooper** [comment]
Resolved by: https://github.com/lyrasis/aspace-jsonmodel-from-format/pull/4
